theme: minima
title: Le Bateau-Livre
author: Alan Leenard
email: your-redanlir@bluewin.ch
description: > # this means to ignore newlines until "baseurl:"
  Leningrad, été 1989 - Le célèbre papyrus Golenitscheff, dit Papyrus 1115, du Musée égyptien de l'Hermitage à Leningrad, a disparu. 
  Le reporter Sammy Lindon arrive dans l'ancienne capitale des tsars pour mener l'enquête.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
