title: Le Bateau-Livre
author: Alan Leenart
email: redanlir@bluewin.ch
description: > # this means to ignore newlines until "baseurl:"
  "Voyager c'est écrire, écrire c'est voyager" - Michel Butor 
  "Je hais les voyages et les explorateurs" - Claude Lévi-Strauss
  "Les voyages... petits vertiges pour couillons" - L. F. Céline
  Ce site est dédié au voyage et à l'écriture
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Rogaton # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
